### ISSUE TITLE
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=8002): Read timed out. (read timeout=20)

### ISSUE THREAD

**Issue by XYZliang** [InternLM/MindSearch#104]
根据[readme](https://github.com/InternLM/MindSearch?tab=readme-ov-file#step2-setup-mindsearch-api)，仅修改了model.py的internlm_server的模型路径为本地
```
❯ CUDA_VISIBLE_DEVICES=2 python -m mindsearch.app --lang cn --model_format internlm_server
INFO:     Started server process [1534721]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8002 (Press CTRL+C to quit)
INFO:     192.168.1.77:8649 - "GET / HTTP/1.1" 200 OK
INFO:     192.168.1.77:8649 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     192.168.1.77:10708 - "GET / HTTP/1.1" 200 OK
INFO:     192.168.1.77:10708 - "GET /openapi.json HTTP/1.1" 200 OK
/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
2024-08-07 09:56:46,645 - lmdeploy - WARNING - model_source: hf_model
2024-08-07 09:56:46,645 - lmdeploy - WARNING - model_name is deprecated in TurbomindEngineConfig and has no effect
2024-08-07 09:56:46,952 - lmdeploy - WARNING - weird json content 
2024-08-07 09:56:49,731 - lmdeploy - WARNING - model_config:

[llama]
model_name = internlm2
tensor_para_size = 1
head_num = 32
kv_head_num = 8
vocab_size = 92544
num_layer = 32
inter_size = 14336
norm_eps = 1e-05
attn_bias = 0
start_id = 1
end_id = 2
session_len = 32768
weight_type = bf16
rotary_embedding = 128
rope_theta = 1000000.0
size_per_head = 128
group_size = 0
max_batch_size = 128
max_context_token_num = 1
step_length = 1
cache_max_entry_count = 0.8
cache_block_seq_len = 128
cache_chunk_size = -1
num_tokens_per_iter = 0
max_prefill_iters = 1
extra_tokens_per_iter = 0
use_context_fmha = 1
quant_policy = 0
max_position_embeddings = 32768
rope_scaling_factor = 0.0
use_logn_attn = 0


[TM][WARNING] [LlamaTritonModel] `max_context_token_num` = 32768.
[TM][WARNING] [LlamaTritonModel] `num_tokens_per_iter` is not set, default to `max_context_token_num` (32768).
2024-08-07 09:56:49,936 - lmdeploy - WARNING - get 259 model params
[WARNING] gemm_config.in is not found; using default GEMM algo                                                                                                                                                                
HINT:    Please open http://0.0.0.0:23333 in a browser for detailed api usage!!!
HINT:    Please open http://0.0.0.0:23333 in a browser for detailed api usage!!!
HINT:    Please open http://0.0.0.0:23333 in a browser for detailed api usage!!!
INFO:     Started server process [1540194]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:23333 (Press CTRL+C to quit)
```

可以看到，在刚启动服务时，后端端口是在 8002 上的，我使用
`streamlit run frontend/mindsearch_streamlit.py`
启动Streamlit前端后（似乎是唯一可用的前端，Gradio和React都存在多次发送请求导致后端请求过多乱套的情况），前端输入问题并发送，此时后端开始正常加载模型。但是在加载后fastapi端口变为了 23333，原有的 8002 失效，但是前端依旧再尝试在8002 端口
```
❯ streamlit run frontend/mindsearch_streamlit.py

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://198.18.0.1:8501
  External URL: http://220.246.88.41:8501

/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/streamlit/watcher/local_sources_watcher.py:210: DeprecationWarning: Importing from `griffe.enumerations` is deprecated. Import from `griffe` directly instead.
  lambda m: list(m.__path__._path),
2024-08-07 09:45:31.899 Uncaught app exception
Traceback (most recent call last):
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/urllib3/connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/urllib3/connectionpool.py", line 538, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/urllib3/connectionpool.py", line 369, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=8002): Read timed out. (read timeout=20)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 75, in exec_func_with_error_handling
    result = func()
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 574, in code_to_exec
    exec(code, module.__dict__)
  File "/data/xyzliang/project/MindSearchCCKS/frontend/mindsearch_streamlit.py", line 319, in <module>
    main()
  File "/data/xyzliang/project/MindSearchCCKS/frontend/mindsearch_streamlit.py", line 314, in main
    update_chat(user_input)
  File "/data/xyzliang/project/MindSearchCCKS/frontend/mindsearch_streamlit.py", line 88, in update_chat
    raw_response = requests.post(url,
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/requests/adapters.py", line 713, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=8002): Read timed out. (read timeout=20)
2024-08-07 09:47:00.426 Uncaught app exception
Traceback (most recent call last):
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/urllib3/connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/urllib3/connectionpool.py", line 538, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/urllib3/connectionpool.py", line 369, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=8002): Read timed out. (read timeout=20)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 75, in exec_func_with_error_handling
    result = func()
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 574, in code_to_exec
    exec(code, module.__dict__)
  File "/data/xyzliang/project/MindSearchCCKS/frontend/mindsearch_streamlit.py", line 319, in <module>
    main()
  File "/data/xyzliang/project/MindSearchCCKS/frontend/mindsearch_streamlit.py", line 314, in main
    update_chat(user_input)
  File "/data/xyzliang/project/MindSearchCCKS/frontend/mindsearch_streamlit.py", line 88, in update_chat
    raw_response = requests.post(url,
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/requests/adapters.py", line 713, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=8002): Read timed out. (read timeout=20)
2024-08-07 09:57:03.523 Uncaught app exception
```
这才是 #102 所异常的原因，而不是所谓的链接超时刷新网页重新查询即可。
根据全局搜索，[只有 model 的这处出现了 23333](https://github.com/InternLM/MindSearch/blob/dfe3e34736cb972aea7071690ff32570638ad9d1/mindsearch/agent/models.py#L19)，也不知道为什么会被用上了

**Comment by XYZliang** [comment]
补充测试：
将本地 8002 端口映射转发到 23333 后重复请求，出现新的报错：
前端：
```
❯ streamlit run frontend/mindsearch_streamlit.py

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://198.18.0.1:8501
  External URL: http://220.246.88.41:8501

/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/streamlit/watcher/local_sources_watcher.py:210: DeprecationWarning: Importing from `griffe.enumerations` is deprecated. Import from `griffe` directly instead.
  lambda m: list(m.__path__._path),
2024-08-07 10:18:14.977 Uncaught app exception
Traceback (most recent call last):
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 75, in exec_func_with_error_handling
    result = func()
  File "/opt/anaconda3/envs/mindsearch/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 574, in code_to_exec
    exec(code, module.__dict__)
  File "/data/xyzliang/project/MindSearchCCKS/frontend/mindsearch_streamlit.py", line 319, in <module>
    main()
  File "/data/xyzliang/project/MindSearchCCKS/frontend/mindsearch_streamlit.py", line 314, in main
    update_chat(user_input)
  File "/data/xyzliang/project/MindSearchCCKS/frontend/mindsearch_streamlit.py", line 94, in update_chat
    for resp in streaming(raw_response):
  File "/data/xyzliang/project/MindSearchCCKS/frontend/mindsearch_streamlit.py", line 54, in streaming
    yield (response['response'], response['current_node'])
KeyError: 'response'
```
后端：
`INFO:     127.0.0.1:36428 - "POST /solve HTTP/1.1" 404 Not Found`

**Comment by liujiangning30** [comment]
23333是后台起的模型服务的端口，mindsearch依然是8002，你重新请求试试呢

**Comment by XYZliang** [comment]
> 23333是后台起的模型服务的端口，mindsearch依然是8002，你重新请求试试呢

实际上 8002 端口已经没有占用了，访问 Ip:8002 已经无法打开。
我尝试重新 git 了项目，问题依旧

**Comment by Harold-lkk** [comment]
后端日志是什么样的

**Comment by liujiangning30** [comment]
资源（cpu，内存）不足可能导致服务挂掉，你可以ps -ef | grep mindsearch.app 看看服务的状态

**Comment by XYZliang** [comment]
> ps -ef | grep mindsearch.app

已经在上面完整提供

**Comment by XYZliang** [comment]
> 后端日志是什么样的

已经在上面完整提供

**Comment by XYZliang** [comment]
> 资源（cpu，内存）不足可能导致服务挂掉，你可以ps -ef | grep mindsearch.app 看看服务的状态

服务和端口占用在，只是访问 ip:8002 已经没法进入 fastapi 页面了，也请求不了

**Comment by XYZliang** [comment]
> 资源（cpu，内存）不足可能导致服务挂掉，你可以ps -ef | grep mindsearch.app 看看服务的状态

资源确定完完全全足够

**Comment by liujiangning30** [comment]
试试重新转发一下8002端口

**Comment by XYZliang** [comment]
已找到稳定复现的方法，我 export 了一个局域网主机上的代理：
```
export http_proxy=http://192.168.1.77:7890 
export https_proxy=http://192.168.1.77:7890
```
这就会导致上述问题发生
如果不export局域网另一台主机的端口做代理，或者用本机的，都不会出现这个情况。

**Comment by liujiangning30** [comment]
可以直接在[BingBrowser](https://github.com/InternLM/MindSearch/blob/b3667655a53b11ad35660b5f275bcc6addb2586c/mindsearch/agent/__init__.py#L46)传proxy
