### ISSUE TITLE
gpt4o finishing the final result problem..

### ISSUE THREAD

**Issue by MyraBaba** [InternLM/MindSearch#130]
I have below errors always in gpt4o .  And always the final answer not finishing and cutting the sentecence or word in the middle ..

Best

ERROR:root:Exception in sync_generator_wrapper: 'content'
Traceback (most recent call last):
  File "/home/bc/Projects/ODS/MindSearch/mindsearch/app.py", line 69, in sync_generator_wrapper
    for response in agent.stream_chat(inputs):
  File "/home/bc/Projects/ODS/MindSearch/mindsearch/agent/mindsearch_agent.py", line 214, in stream_chat
    for model_state, response, _ in self.llm.stream_chat(
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lagent/llms/openai.py", line 151, in stream_chat
    for text in self._stream_chat(messages, **gen_params):
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lagent/llms/openai.py", line 288, in streaming
    yield choice['delta']['content']
KeyError: 'content'

**Comment by liujiangning30** [comment]
https://github.com/InternLM/lagent/pull/226
