### ISSUE TITLE
ERROR:root:Exception in sync_generator_wrapper: Operation on the closed queue is forbidden/ ERROR:asyncio:Future exception was never retrieved

### ISSUE THREAD

**Issue by AlexaOscar** [InternLM/MindSearch#136]
follow step: https://github.com/InternLM/Tutorial/tree/camp3/docs/EasterEgg/MindSearch
MindSearchDuck

**ERROR:root:Exception in sync_generator_wrapper: Operation on the closed queue is forbidden**
Traceback (most recent call last):
  File "/share/demo/MindSearchDuck/mindsearch/app.py", line 69, in sync_generator_wrapper
    queue.sync_q.put(response)
  File "/share/pre_envs/mindsearch/lib/python3.10/site-packages/janus/__init__.py", line 371, in put
    self._parent._check_closing()
  File "/share/pre_envs/mindsearch/lib/python3.10/site-packages/janus/__init__.py", line 269, in _check_closing
    raise RuntimeError("Operation on the closed queue is forbidden")
RuntimeError: Operation on the closed queue is forbidden
**ERROR:asyncio:Future exception was never retrieved**
future: <Future finished exception=RuntimeError('Operation on the closed queue is forbidden')>
Traceback (most recent call last):
  File "/share/pre_envs/mindsearch/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/share/demo/MindSearchDuck/mindsearch/app.py", line 75, in sync_generator_wrapper
    queue.sync_q.put(None)
  File "/share/pre_envs/mindsearch/lib/python3.10/site-packages/janus/__init__.py", line 371, in put
    self._parent._check_closing()
  File "/share/pre_envs/mindsearch/lib/python3.10/site-packages/janus/__init__.py", line 269, in _check_closing
    raise RuntimeError("Operation on the closed queue is forbidden")
RuntimeError: Operation on the closed queue is forbidden

**Comment by liujiangning30** [comment]
https://github.com/InternLM/MindSearch/pull/84
