### ISSUE TITLE
前端每次显示一半就截断

### ISSUE THREAD

**Issue by ssrheart425** [InternLM/MindSearch#148]
后端一切正常，直接返回结果，在前端显示有问题，以下是后端的日志，输入的问题是："周杰伦是怎么写歌的？"，使用的模型是gpt4o-mini，前端使用react。

```
INFO:     103.151.172.34:9972 - "POST /solve HTTP/1.1" 200 OK
<|action_start|><|interpreter|>```python
graph = WebSearchGraph()
graph.add_root_node(node_content="周杰伦是怎么写歌的?", node_name="root") # Add the original question as the root node
graph.add_node(
        node_name="周杰伦的创作灵感", # The node name should be meaningful
        node_content="周杰伦的创作灵感来源于哪里?")
graph.add_node(
        node_name="周杰伦的歌词风格", # The node name should be meaningful
        node_content="周杰伦的歌词风格是什么样的?")
graph.add_node(
        node_name="周杰伦的音乐创作过程", # The node name should be meaningful
        node_content="周杰伦的音乐创作过程是怎样的?")
graph.add_edge(start_node="root", end_node="周杰伦的创作灵感")
graph.add_edge(start_node="root", end_node="周杰伦的歌词风格")
graph.add_edge(start_node="root", end_node="周杰伦的音乐创作过程")
# Get node info
graph.node("周杰伦的创作灵感"), graph.node("周杰伦的歌词风格"), graph.node("周杰伦的音乐创作过程")
```<|action_end|>
current query: ## Final Problem
周杰伦是怎么写歌的?
## Current Problem
周杰伦的创作灵感来源于哪里?
current query: ## Final Problem
周杰伦是怎么写歌的?
## Current Problem
周杰伦的歌词风格是什么样的?

current query: ## Final Problem
周杰伦是怎么写歌的?
## Current Problem
周杰伦的音乐创作过程是怎样的?


周杰伦（Jay Chou）是华语流行音乐的代表性人物之一，他的创作灵感来源于多个方面，主要包括以下几点：

1. **生活经历**：周杰伦的许多歌曲都反映了他的个人经历和情感，例如家庭、爱情和友谊。他在音乐中融入了自己对生活的观察和感悟，使得他的作品更加真实和感人。

2. **电影和文学**：周杰伦对电影和文学有着浓厚的兴趣。他的许多歌曲灵感来自于电影情节或文学作品，特别是古典文学和现代小说。这使得他的歌词常常具有故事性和画面感，例如《青花瓷》就受到中国古典文化的影响。

3. **音乐风格的融合**：周杰伦善于将不同的音乐风格结合在一起，包括嘻哈、R&B、古典音乐等。他的这种风格融合不仅体现在曲调上，也影响了他的歌词创作。他常常通过不同的音乐元素表达情感和主题。

4. **社会现象**：周杰伦的作品也受到社会现象和时事的影响。他会将社会问题、青年人的困惑和生活中的不公正等主题融入到他的歌词中，以此引起听众的共鸣。

5. **周围人的影响**：周杰伦在创作过程中常常受到身边人的启发，包括朋友、家人以及合作的音乐人。他会与他们交流，讨论音乐和生活，从而获得灵感。

总的来说，周杰伦的创作灵感来源于丰富的生活体验、对文化的热爱以及对社会的关注，这使得他的音乐作品充满了深度和广度。
周杰伦的音乐创作过程是非常独特和个人化的，通常包括以下几个关键步骤：

1. **灵感来源**：周杰伦的创作灵感来自于生活中的各种经历，包括个人情感、社会现象、历史文化等。他常常会在日常生活中寻找创作素材，许多歌词和旋律都源于他的真实体验。

2. **旋律创作**：周杰伦擅长使用钢琴和吉他来创作旋律。他通常会先创作旋律，然后再根据旋律的感觉来填词。这种方法使得他的音乐具有鲜明的旋律感和节奏感。

3. **歌词创作**：在创作歌词时，周杰伦喜欢使用丰富的意象和比喻，歌词中常常融入诗意和故事性。他的歌词风格多样，从浪漫情歌到社会批判，都能找到他的身影。

4. **编曲与制作**：周杰伦不仅是歌手，还是一位优秀的制作人。他在编曲过程中会考虑各种乐器的搭配，以及如何通过不同的音效来增强歌曲的表现力。他常常与他的团队合作，精心打磨每一首歌曲的细节。

5. **录音与演唱**：在录音阶段，周杰伦会对自己的演唱进行多次尝试，确保每个音符都能完美表达他的情感。他对音乐的细致要求使得每首歌都充满了个人特色。

6. **反复修改**：周杰伦对自己的作品有着严格的要求，往往会经过多次修改和调整，直到他自己满意为止。

周杰伦的创作过程展示了他对音乐的热爱和执着，使得他的歌曲能够在华语乐坛中脱颖而出，赢得了广泛的认可和喜爱。
周杰伦的歌词风格独特且多样化，以下是一些主要特点：

1. **融合传统与现代**：周杰伦的歌词常常融合传统文化元素和现代流行音乐，体现了中国传统文化的韵味，同时又不失现代感。例如，他在《东风破》中使用了古典诗词的意象。

2. **叙事性强**：他的歌词通常具备较强的叙事性，常常讲述故事或描绘情景，如《稻香》通过讲述乡村生活传达对简单生活的向往。

3. **情感丰富**：周杰伦的歌词中充满了丰富的情感，从爱情、友情到对生活的感悟，他都能通过细腻的文字表达出来。比如在《不能说的秘密》中，歌词表达了深沉的爱情与遗憾。

4. **使用隐喻和比喻**：周杰伦擅长使用隐喻和比喻，使得歌词更具诗意和深度。他的作品中常常能够找到意象丰富的表达，如《晴天》中用天气变化象征心情的起伏。

5. **俚语和口语化**：他的歌词常常使用日常生活中的俚语和口语，使得歌曲更加贴近年轻人的生活。例如《双截棍》中就融入了不少街头文化的元素。

6. **多样的音乐风格**：周杰伦的歌词风格也随着音乐风格的变化而变化，他的作品涵盖了R&B、Hip-Hop、古典等多种音乐风格，使得歌词在不同风格下展现出不同的魅力。

这些特点使得周杰伦的歌词不仅具有高度的艺术性，还能够引起广泛的共鸣和情感共鸣。
<|action_start|><|interpreter|>```python
# Adding response node with the information gathered from the previous nodes
graph.add_response_node(node_name="response")
```<|action_end|>
response {"id":"chatcmpl-9vgcFi13i9Ie1w0SOsj6ULf9UMMlP","object":"chat.completion.chunk","created":1723535539,"model":"gpt-4o-mini-2024-07-18","system_fingerprint":"fp_48196bc67a","choices":[{"index":0,"delta":{},"logprobs":null,"finish_reason":"length"}]} lead to exception of 'content'
周杰伦（Jay Chou）是一位极具影响力的华语流行音乐创作人，他的歌曲创作过程充满了个人风格与独特的艺术表达。以下是关于他创作歌曲的几个关键方面。

### 1. 创作灵感

周杰伦的创作灵感来源广泛，主要包括以下几个方面：

- **生活经历**：他的许多歌曲反映了个人经历与情感，例如家庭、爱情和友谊。这些真实的生活观察使得他的作品更具共鸣和感动[[1]]。
  
- **电影与文学**：周杰伦对电影和文学有浓厚的兴趣，许多歌词灵感源自于电影情节或文学作品，尤其是古典文化的影响[[1]]。

- **音乐风格融合**：他擅长将不同音乐风格融合，如嘻哈、R&B和古典音乐，这种多样性在他的歌词中也得以体现[[1]]。

- **社会现象**：周杰伦的作品关注社会问题与时事，歌词中常常反映青年人的困惑和生活中的不公正现象[[1]]。

- **周围人的影响**：创作过程中，他受到朋友、家人及合作音乐人的启发，通过交流获得灵感[[1]]。

### 2. 歌词风格

周杰伦的歌词风格独特且多样，主要特点包括：

- **融合传统与现代**：他的歌词常常结合传统文化元素与现代流行音乐，体现了中国传统文化的韵味[[2]]。

- **叙事性强**：周杰伦的歌词通常具有强烈的叙事性，常通过讲述故事或描绘情景来传达情感[[2]]。

- **情感丰富**：歌词中充满细腻的情感表达，涵盖爱情、友情以及对生活的深刻感悟[[2]]。

- **使用隐喻与比喻**：他擅长运用隐喻和比喻，使歌词更具诗意与深度[[2]]。

- **俚语与口语化**：周杰伦的歌词常使用日常生活中的俚语，使得歌曲更贴近年轻人的生活[[2]]。

-
```

前端日志如下：

```
 INFO  Accepting connections at http://localhost:8080
 HTTP  8/13/2024 7:47:18 AM 103.151.172.34 GET /
 HTTP  8/13/2024 7:47:18 AM 103.151.172.34 Returned 304 in 83 ms
 HTTP  8/13/2024 7:47:18 AM 103.151.172.34 GET /assets/index-ab4095ce.css
 HTTP  8/13/2024 7:47:18 AM 103.151.172.34 Returned 304 in 3 ms
 HTTP  8/13/2024 7:47:18 AM 103.151.172.34 GET /assets/index-26b4a389.js
 HTTP  8/13/2024 7:47:18 AM 103.151.172.34 Returned 304 in 6 ms
 HTTP  8/13/2024 7:47:19 AM 103.151.172.34 GET /assets/sendIcon-79e92e84.svg
 HTTP  8/13/2024 7:47:19 AM 103.151.172.34 Returned 304 in 3 ms
 HTTP  8/13/2024 7:47:19 AM 103.151.172.34 GET /assets/logo-38417354.svg
 HTTP  8/13/2024 7:47:19 AM 103.151.172.34 Returned 304 in 3 ms
 HTTP  8/13/2024 7:47:19 AM 103.151.172.34 GET /assets/background-95159880.png
 HTTP  8/13/2024 7:47:19 AM 103.151.172.34 Returned 304 in 2 ms
 HTTP  8/13/2024 7:47:19 AM 103.151.172.34 GET /favicon.ico
 HTTP  8/13/2024 7:47:19 AM 103.151.172.34 Returned 304 in 2 ms
 HTTP  8/13/2024 7:47:32 AM 103.151.172.34 GET /assets/pack-up-ad0b3cbc.svg
 HTTP  8/13/2024 7:47:32 AM 103.151.172.34 Returned 304 in 2 ms
 HTTP  8/13/2024 7:47:36 AM 103.151.172.34 GET /assets/show-right-icon-12c14da5.png
 HTTP  8/13/2024 7:47:36 AM 103.151.172.34 Returned 304 in 5 ms
 HTTP  8/13/2024 7:48:51 AM 103.151.172.34 GET /assets/pack-up-ad0b3cbc.svg
 HTTP  8/13/2024 7:48:51 AM 103.151.172.34 Returned 304 in 1 ms
 HTTP  8/13/2024 7:49:07 AM 103.151.172.34 GET /assets/pack-up-ad0b3cbc.svg
 HTTP  8/13/2024 7:49:07 AM 103.151.172.34 Returned 304 in 2 ms
 HTTP  8/13/2024 7:49:17 AM 103.151.172.34 GET /assets/show-right-icon-12c14da5.png
 HTTP  8/13/2024 7:49:17 AM 103.151.172.34 Returned 304 in 1 ms
 HTTP  8/13/2024 7:52:07 AM 103.151.172.34 GET /assets/pack-up-ad0b3cbc.svg
 HTTP  8/13/2024 7:52:07 AM 103.151.172.34 Returned 304 in 3 ms
 HTTP  8/13/2024 7:52:29 AM 103.151.172.34 GET /assets/show-right-icon-12c14da5.png
 HTTP  8/13/2024 7:52:29 AM 103.151.172.34 Returned 304 in 2 ms
```

还有一个问题，就是使用gpt4o的时候，输入问题之后，当有一个字出现在网页右侧白色部分时候，网页整个就会白屏卡死，后端还是正常在运行。
用最新main分支，一样的配置文件内容，根本运行不了，显示一下加载的圈就没动静了，前后端日志都没有反应。
而且F12查看控制台一直有format error报错

```
format error----- SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Ot (index-26b4a389.js:72:599992)
    at onmessage (index-26b4a389.js:72:600839)
    at index-26b4a389.js:72:590952
    at index-26b4a389.js:72:590776
    at LH (index-26b4a389.js:72:590495)
    at async x (index-26b4a389.js:72:592546)
```

**Comment by ssrheart425** [comment]
拉取最新的main分支，使用gpt4o-mini，修改了KeyError问题，显示如下：


![image](https://github.com/user-attachments/assets/6ab381e4-4994-4bab-9358-844a21ff9231)

后端日志：



```
INFO:     127.0.0.1:14907 - "POST /solve HTTP/1.1" 200 OK
我们我们可以可以将将““周周杰杰伦伦是是怎么怎么写写歌歌的的””这个这个问题问题拆拆分分为为几个几个具体具体的的子子问题问
题，以，以便便进行进行搜索搜索。。以下以下是是可能可能的的子子问题问题：

：

11.. 周 周杰杰伦伦的的创创作作灵灵感感来源来源是什么是什么？
？
22.. 周 周杰杰伦伦在在写写歌歌时时使用使用的的常常见见主题主题有哪些有哪些？
？
33.. 周 周杰杰伦伦的的歌曲歌曲创创作作流程流程是是怎样怎样的的？
？
44.. 周 周杰杰伦伦在在作作词词时时通常通常关注关注哪些哪些方面方面？
？
55.. 周 周杰杰伦伦的的音乐音乐风风格格特点特点是什么是什么？

？

我我将将首先首先添加添加根根节点节点，然后，然后逐逐步步添加添加这些这些子子问题问题。。接接下来下来我我会会添加添加第
第一个一个子子问题问题的的节点节点。。



<<||actionaction_start_start||><><||interinterpreterpreter||>>``````pythonpython

graphgraph = = Web WebSearchSearchGraphGraph()
()
graphgraph.add.add_root_root_node_node(node(node_content_content="="周周杰杰伦伦是是怎么怎么写写歌歌的的?",?", node node_name_name="="rootroot")") # # 添加 添加原原始始问题问题作为作为根根节点节点

graphgraph.add.add_node_node(
(
               node node_name_name="="创创作作灵灵感感",", # # 节 节点点名称名称

               node node_content_content="="周周杰杰伦伦的的创创作作灵灵感感来源来源是什么是什么？？")
")
``````<<||actionaction_end_end||>>
```

**Comment by liujiangning30** [comment]
核心问题在于模型没有遵循工具调用的协议，你可以进一步丰富[fewshot](https://github.com/InternLM/MindSearch/blob/1f7a75dbfb56433e2533357d63f03ad48c46612e/mindsearch/agent/mindsearch_prompt.py#L36C1-L36C20)

**Comment by hnch07** [comment]
请问 你们有遇到过跑起来前后端都没有报错 但是不创建节点吗

![Image](https://github.com/user-attachments/assets/9927c48d-5be8-4436-8dc6-f23f6758d967)像这样就没有反应了

这是后端输出一篇空白

![Image](https://github.com/user-attachments/assets/02411c8d-07e1-4226-ba0c-c8b055e760e9) 也没报错
这是前端也没有反应

![Image](https://github.com/user-attachments/assets/61b138d4-fd96-450b-9416-e71cf034dc53)
