### ISSUE TITLE
back end failed to launch on Huggingface due to unexpected griffe version

### ISSUE THREAD

**Issue by leagend** [InternLM/MindSearch#173]
Try to launch mindsearch/app.py on Huggingface as part of gradio app.
After installed the required modules as mentioned in requirements.txt.
The app failed to launch and got the following log in container:

Traceback (most recent call last): File "/home/user/app/app.py", line 11, in <module> from lagent.schema import AgentStatusCode File "/usr/local/lib/python3.10/site-packages/lagent/__init__.py", line 2, in <module> from .actions import * # noqa: F401, F403 File "/usr/local/lib/python3.10/site-packages/lagent/actions/__init__.py", line 3, in <module> from .action_executor import ActionExecutor File "/usr/local/lib/python3.10/site-packages/lagent/actions/action_executor.py", line 4, in <module> from .base_action import BaseAction File "/usr/local/lib/python3.10/site-packages/lagent/actions/base_action.py", line 16, in <module> from griffe.enumerations import DocstringSectionKind ModuleNotFoundError: No module named 'griffe.enumerations'

I tried to append griffe==0.48 to requirements.txt can solve this issue.

**Comment by leagend** [comment]
The Pull Request https://github.com/InternLM/MindSearch/pull/174 is target to fix it.

**Comment by leagend** [comment]
@BetterSnail @LCorleone @zehuichen123 @Harold-lkk please help to review this PR.

**Comment by liujiangning30** [comment]
We've fixed this in toolkit `lagent`, check [this](https://github.com/InternLM/lagent/pull/237/files).

**Comment by leagend** [comment]
OK
