### ISSUE TITLE
Gradio version throws up error for complex queries

### ISSUE THREAD

**Issue by Hemang999** [InternLM/MindSearch#176]
Hi,

I am mainly using the gradio version of mindsearch. It works fine for simple queries (eg. find _xyz_ recipe for me) but throws up the following error for complex queries which requires searching the internet extensively and researching various webpages (eg. find the latest GenAI research papers and/or techniques to solve _xyz_ problem) after the very first response which is writing out the code for constructing the graph:-

ERROR:mindsearch.agent.mindsearch_agent:Error executing code:
Traceback (most recent call last):
  File "C:\Users\heman\Downloads\MindSearch\mindsearch\agent\mindsearch_agent.py", line 362, in run_command
    assert plan_graph is not None
AssertionError
Exception in thread Thread-2 (run_command):
Traceback (most recent call last):
  File "C:\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
ERROR:root:Exception in sync_generator_wrapper: 'NoneType' object has no attribute 'searcher_resp_queue'
Traceback (most recent call last):
  File "C:\Users\heman\Downloads\MindSearch\mindsearch\app.py", line 73, in sync_generator_wrapper
    for response in agent.stream_chat(inputs):
  File "C:\Users\heman\Downloads\MindSearch\mindsearch\agent\mindsearch_agent.py", line 237, in stream_chat
    yield from self._process_code(agent_return, inner_history,
  File "C:\Users\heman\Downloads\MindSearch\mindsearch\agent\mindsearch_agent.py", line 261, in _process_code
    for node_name, node, adj in self.execute_code(
  File "C:\Users\heman\Downloads\MindSearch\mindsearch\agent\mindsearch_agent.py", line 382, in execute_code
    item = self.local_dict.get('graph').searcher_resp_queue.get(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'searcher_resp_queue'
    self.run()
  File "C:\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\heman\Downloads\MindSearch\mindsearch\agent\mindsearch_agent.py", line 362, in run_command
    assert plan_graph is not None
AssertionError

I am running it on windows 11 in a virtual environment on vs code.

**Comment by liujiangning30** [comment]
[InternLM2.5 series](https://huggingface.co/internlm/internlm2_5-7b-chat) are specifically optimized to provide superior performance within the MindSearch framework. You may need to optimize the [fewshot](https://github.com/InternLM/MindSearch/blob/b8322757a8b24088c35633dfd48ba37ab9e88e80/mindsearch/agent/mindsearch_prompt.py#L295) so that it follows the response protocol for other open-source models.

**Comment by Hemang999** [comment]
> [InternLM2.5 series](https://huggingface.co/internlm/internlm2_5-7b-chat) are specifically optimized to provide superior performance within the MindSearch framework. You may need to optimize the [fewshot](https://github.com/InternLM/MindSearch/blob/b8322757a8b24088c35633dfd48ba37ab9e88e80/mindsearch/agent/mindsearch_prompt.py#L295) so that it follows the response protocol for other open-source models. In addition, we will continue to optimize the ability of the InternLM series model on mindsearch.

But isn't internLM2.5 more suitable for Chinese? I want the best possible responses in english.
