### ISSUE TITLE
运行msdl后报错

### ISSUE THREAD

**Issue by Cormac315** [InternLM/MindSearch#198]
错误信息：
Traceback (most recent call last):
  File "/usr/local/bin/msdl", line 33, in <module>
    sys.exit(load_entry_point('msdl', 'console_scripts', 'msdl')())
  File "/www/wwwroot/MindSearch/docker/msdl/__main__.py", line 159, in main
    setup_i18n()
  File "/www/wwwroot/MindSearch/docker/msdl/i18n.py", line 35, in setup_i18n
    set_env_variable("LAUNCHER_INTERACTION_LANGUAGE", system_language)
  File "/www/wwwroot/MindSearch/docker/msdl/i18n.py", line 17, in set_env_variable
    set_key(dotenv_file, var_name, value)
  File "/usr/local/lib/python3.10/dist-packages/dotenv/main.py", line 183, in set_key
    with rewrite(dotenv_path, encoding=encoding) as (source, dest):
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/dotenv/main.py", line 149, in rewrite
    raise error from None
  File "/usr/local/lib/python3.10/dist-packages/dotenv/main.py", line 140, in rewrite
    with open(path, encoding=encoding) as source:
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by Cormac315** [comment]
已解决，设置环境变量LAUNCHER_INTERACTION_LANGUAGE="zh_CN"后运行msdl即可
