### ISSUE TITLE
python3.12 运行的时候报错

### ISSUE THREAD

**Issue by fuckqqcom** [InternLM/MindSearch#199]
(mind_search) [qa@a mind_search]$ python -m mindsearch.app --lang cn --model_format  gpt4 --search_engine DuckDuckGoSearch
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/qa/xiaohan/mind_search/mindsearch/app.py", line 11, in <module>
    from lagent.schema import AgentStatusCode
  File "/home/qa/anaconda3/envs/mind_search/lib/python3.12/site-packages/lagent/__init__.py", line 2, in <module>
    from .actions import *  # noqa: F401, F403
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qa/anaconda3/envs/mind_search/lib/python3.12/site-packages/lagent/actions/__init__.py", line 3, in <module>
    from .action_executor import ActionExecutor
  File "/home/qa/anaconda3/envs/mind_search/lib/python3.12/site-packages/lagent/actions/action_executor.py", line 4, in <module>
    from .base_action import BaseAction
  File "/home/qa/anaconda3/envs/mind_search/lib/python3.12/site-packages/lagent/actions/base_action.py", line 14, in <module>
    from class_registry import AutoRegister, ClassRegistry
ImportError: cannot import name 'AutoRegister' from 'class_registry' (/home/qa/anaconda3/envs/mind_search/lib/python3.12/site-packages/class_registry/__init__.py)

**Comment by hpyou** [comment]
同样的报错
(venv) PS D:\Codes\MindSearch> python -m mindsearch.app --lang en --model_format internlm_server --search_engine DuckDuckGoSearch
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Codes\MindSearch\mindsearch\app.py", line 11, in <module>
    from lagent.schema import AgentStatusCode
  File "D:\Codes\MindSearch\venv\Lib\site-packages\lagent\__init__.py", line 2, in <module>
    from .actions import *  # noqa: F401, F403
    ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Codes\MindSearch\venv\Lib\site-packages\lagent\actions\__init__.py", line 3, in <module>
    from .action_executor import ActionExecutor
  File "D:\Codes\MindSearch\venv\Lib\site-packages\lagent\actions\action_executor.py", line 4, in <module>
    from .base_action import BaseAction
  File "D:\Codes\MindSearch\venv\Lib\site-packages\lagent\actions\base_action.py", line 14, in <module>
    from class_registry import AutoRegister, ClassRegistry
ImportError: cannot import name 'AutoRegister' from 'class_registry' (D:\Codes\MindSearch\venv\Lib\site-packages\class_registry\__init__.py)

**Comment by fuckqqcom** [comment]
> pip install phx-class-registry==4.1.0 可以解决问题 ![image](https://private-user-images.githubusercontent.com/15992591/366044368-a131da18-5902-4adc-ab2a-4d811438474f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMzEzNDAsIm5iZiI6MTcyNjAzMTA0MCwicGF0aCI6Ii8xNTk5MjU5MS8zNjYwNDQzNjgtYTEzMWRhMTgtNTkwMi00YWRjLWFiMmEtNGQ4MTE0Mzg0NzRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA1MDQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNjc2ZTYwMmUyOGQ3MmEyMjMzMTljZmJlNjM2MWU2NGI4YTI5NTI2OTY2YjMwZDU4MmM4ZDFmODNiZjk4YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Awz5ba4F7DyPRtL83yrE36D38hYv_LNuyxNhccRpEbs)

感谢，忘了关了，我安装的更旧的版本解决了
