### ISSUE TITLE
ImportError: cannot import name 'AutoRegister' from 'class_registry' (/opt/conda/envs/mindsearch/lib/python3.10/site-packages/class_registry/__init__.py)

### ISSUE THREAD

**Issue by codefd** [InternLM/MindSearch#202]
/workspaces/mindsearch/MindSearch (b832275) $ python -m mindsearch.app --lang cn --model_format internlm_silicon --search_engine DuckDuckGoSearch
Traceback (most recent call last):
  File "/opt/conda/envs/mindsearch/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/mindsearch/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspaces/mindsearch/MindSearch/mindsearch/app.py", line 11, in <module>
    from lagent.schema import AgentStatusCode
  File "/opt/conda/envs/mindsearch/lib/python3.10/site-packages/lagent/__init__.py", line 2, in <module>
    from .actions import *  # noqa: F401, F403
  File "/opt/conda/envs/mindsearch/lib/python3.10/site-packages/lagent/actions/__init__.py", line 3, in <module>
    from .action_executor import ActionExecutor
  File "/opt/conda/envs/mindsearch/lib/python3.10/site-packages/lagent/actions/action_executor.py", line 4, in <module>
    from .base_action import BaseAction
  File "/opt/conda/envs/mindsearch/lib/python3.10/site-packages/lagent/actions/base_action.py", line 14, in <module>
    from class_registry import AutoRegister, ClassRegistry
ImportError: cannot import name 'AutoRegister' from 'class_registry' (/opt/conda/envs/mindsearch/lib/python3.10/site-packages/class_registry/__init__.py)

**Comment by effectzhang** [comment]
我也遇到这个问题了，有解法吗

**Comment by Ming-jiayou** [comment]
遇到一样的问题

**Comment by daogu** [comment]
`from class_registry import AutoRegister, ClassRegistry`
报错的AutoRegister 换成下面的
`from class_registry.auto_register import AutoRegister`

**Comment by leon21c** [comment]
要再安装个依赖 pip install class_registry

**Comment by bombert** [comment]
> 要再安装个依赖 pip install class_registry

爱你哦
