### ISSUE TITLE
按照readme操作流程走完一遍，运行后端项目没有报错，只显示提示信息在后端也出现错误提示：OSError: [WinError 126] 找不到指定的模块。 Error loading "C:\Users\zzcst.conda\envs\mindsearch\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

### ISSUE THREAD

**Issue by 2721031254a** [InternLM/MindSearch#231]
按照readme操作流程走完一遍，运行后端项目没有报错，只显示提示信息：(mindsearch) C:\研究生\研究生所学知识技术\mindsearch\MindSearch>python -m mindsearch.app --lang en --model_format internlm_server --search_engine DuckDuckGoSearch
INFO:     Started server process [158444]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8002 (Press CTRL+C to quit)。运行测试程序backend_example.py时候出现错误：(mindsearch) C:\研究生\研究生所学知识技术\mindsearch\MindSearch>python backend_example.py
Traceback (most recent call last):
  File "C:\研究生\研究生所学知识技术\mindsearch\MindSearch\backend_example.py", line 34, in <module>
    get_response(query)
  File "C:\研究生\研究生所学知识技术\mindsearch\MindSearch\backend_example.py", line 26, in get_response
    response_data = json.loads(decoded)
  File "C:\Users\zzcst\.conda\envs\mindsearch\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\zzcst\.conda\envs\mindsearch\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\zzcst\.conda\envs\mindsearch\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)。在后端也出现错误提示：OSError: [WinError 126] 找不到指定的模块。 Error loading "C:\Users\zzcst\.conda\envs\mindsearch\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

**Comment by chuanzhubin** [comment]
我是可以跑通 streamlit版本， React版本不行

**Comment by Harold-lkk** [comment]
可以用新版本试一下
