### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by hjs0808** [InternLM/MindSearch#261]
This problem always occurs, and when it does, the front-end does not respond, and sometimes it is normal and sometimes it reports an error
How should I solve it ！！！！

error messages：
2024-11-19 11:16:03,616 - app.py[line:72] - ERROR: Exception in sync_generator_wrapper: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/model/ms/mindsearch/app.py", line 69, in sync_generator_wrapper
    for response in agent.stream_chat(inputs):
  File "/home/model/ms/mindsearch/agent/mindsearch_agent.py", line 237, in stream_chat
    yield from self._process_code(agent_return, inner_history,
  File "/home/model/ms/mindsearch/agent/mindsearch_agent.py", line 284, in _process_code
    reference, references_url = self._generate_reference(
  File "/home/model/ms/mindsearch/agent/mindsearch_agent.py", line 315, in _generate_reference
    ref_results = agent_return.nodes[node_name]['detail'].actions[
TypeError: 'NoneType' object is not subscriptable

**Comment by Harold-lkk** [comment]
please use latest version

**Comment by hjs0808** [comment]
> please use latest version

it works , thanks, but I have another question, the react web interface doesn't seem to be responding, What shall I do?

**Comment by hjs0808** [comment]
> please use latest version

streamlit is  normal

**Comment by Harold-lkk** [comment]
![image](https://github.com/user-attachments/assets/818b029c-b3be-477a-be21-64f39d03f900)

**Comment by hjs0808** [comment]
![image](https://github.com/user-attachments/assets/1dcd9e81-3135-45a9-a2d4-78694980c09c)
![image](https://github.com/user-attachments/assets/8bcdb233-b8cf-478a-93ab-20dac66132b6)

Thank you, it started working successfully, but there were two errors when i was use. Is this mistake serious? How should I solve this problem

**Comment by braisedpork1964** [comment]
Have you checked if there's any syntax error in the code block from the planner's response? Most errors above are caused by its coding capability.
