### ISSUE TITLE
【BUG】AttributeError: 'NoneType' object has no attribute 'searcher_resp_queue'`

### ISSUE THREAD

**Issue by datalee** [InternLM/MindSearch#36]
`首先，我们需要计算从2024年3月23日到2024年8月1日的天数。这可以通过计算两个日期之间的天数差来实现。<|action_start|><|interpreter|>
```python
from datetime import datetime

# 定义起始日期和结束日期
start_date = datetime(2024, 3, 23)
end_date = datetime(2024, 8, 1)

# 计算天数差
days_difference = (end_date - start_date).days
days_difference
```
ERROR:mindsearch.agent.mindsearch_agent:Error executing code: 
Traceback (most recent call last):
  File "/Mindsearch/tmp/pycharm_project_829/mindsearch/agent/mindsearch_agent.py", line 349, in run_command
    assert plan_graph is not None
           ^^^^^^^^^^^^^^^^^^^^^^
AssertionError
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=AttributeError("'NoneType' object has no attribute 'searcher_resp_queue'")>
Traceback (most recent call last):
  File "/anaconda311/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Mindsearch/tmp/pycharm_project_829/mindsearch/app.py", line 68, in sync_generator_wrapper
    for response in agent.stream_chat(inputs):
  File "/Mindsearch/tmp/pycharm_project_829/mindsearch/agent/mindsearch_agent.py", line 234, in stream_chat
    yield from self._process_code(
  File "/Mindsearch/tmp/pycharm_project_829/mindsearch/agent/mindsearch_agent.py", line 260, in _process_code
    for node_name, node, adj in self.execute_code(
  File "/Mindsearch/tmp/pycharm_project_829/mindsearch/agent/mindsearch_agent.py", line 368, in execute_code
    item = self.local_dict.get('graph').searcher_resp_queue.get(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'searcher_resp_queue'
`

**Comment by Harold-lkk** [comment]
这个是 InternLM 模型的问题，因为 InternLM 本身也具备代码解释器的功能 触发Token 也是 <|interpreter|> 所以有点串台了，我们实现的代码里没有对这个内容做兼容，如果能够运行代码，并且拿到返回实际也是能得到正确结果的

**Comment by datalee** [comment]
> 这个是 InternLM 模型的问题，因为 InternLM 本身也具备代码解释器的功能 触发Token 也是 <|interpreter|> 所以有点串台了，我们实现的代码里没有对这个内容做兼容，如果能够运行代码，并且拿到返回实际也是能得到正确结果的

我发现写的代码最后没有print(days_difference),会导致exec(cmd, globals(), self.local_dict)没有结果返回，所以出现了问题

**Comment by datalee** [comment]
这块代码执行的内核能否改成jupyter的

**Comment by Harold-lkk** [comment]
我们现在拿 graph 这个句柄比较 trick 是在相同进程运行代码然后是共享的local和global dict然后去local dict 拿我们想要的字段，改成jupyter 实现起来有点麻烦

**Comment by Harold-lkk** [comment]
实际你在local dict  那days_difference 这个变量还是有的

**Comment by Harold-lkk** [comment]
这个好像如果hardcode 判断graph相关的操作在不在生成代码中，切换不同的执行环境是可以在做到的，可以实验一下，提个 PR 呀
