### ISSUE TITLE
error from streamlit

### ISSUE THREAD

**Issue by MyraBaba** [InternLM/MindSearch#54]
streamlit run frontend/mindsearch_streamlit.py

python -m mindsearch.app --lang en --model_format GPTAPI

write hello in web result:

Traceback (most recent call last):
  File "/home/bc/Projects/meta_expert/venvMaeteJag/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 75, in exec_func_with_error_handling
    result = func()
  File "/home/bc/Projects/meta_expert/venvMaeteJag/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 574, in code_to_exec
    exec(code, module.__dict__)
  File "/home/bc/Projects/ODS/MindSearch/frontend/mindsearch_streamlit.py", line 319, in <module>
    main()
  File "/home/bc/Projects/ODS/MindSearch/frontend/mindsearch_streamlit.py", line 314, in main
    update_chat(user_input)
  File "/home/bc/Projects/ODS/MindSearch/frontend/mindsearch_streamlit.py", line 94, in update_chat
    for resp in streaming(raw_response):
  File "/home/bc/Projects/ODS/MindSearch/frontend/mindsearch_streamlit.py", line 53, in streaming
    response = json.loads(decoded)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by MyraBaba** [comment]
for GPT-4


  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/bc/Projects/ODS/MindSearch/mindsearch/app.py", line 122, in run
    agent = init_agent(lang=args.lang, model_format=args.model_format)
  File "/home/bc/Projects/ODS/MindSearch/mindsearch/agent/__init__.py", line 24, in init_agent
    llm_cfg = llm_cfg.copy()
AttributeError: type object 'GPTAPI' has no attribute 'copy'

**Comment by MyraBaba** [comment]
add:



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc/Projects/meta_expert/venvMaeteJag/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 75, in exec_func_with_error_handling
    result = func()
  File "/home/bc/Projects/meta_expert/venvMaeteJag/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 574, in code_to_exec
    exec(code, module.__dict__)
  File "/home/bc/Projects/ODS/MindSearch/frontend/mindsearch_streamlit.py", line 319, in <module>
    main()
  File "/home/bc/Projects/ODS/MindSearch/frontend/mindsearch_streamlit.py", line 314, in main
    update_chat(user_input)
  File "/home/bc/Projects/ODS/MindSearch/frontend/mindsearch_streamlit.py", line 234, in update_chat
    if st.session_state['session_info_temp']:
  File "/home/bc/Projects/meta_expert/venvMaeteJag/lib/python3.10/site-packages/streamlit/runtime/state/session_state_proxy.py", line 98, in __getitem__
    return get_session_state()[key]
  File "/home/bc/Projects/meta_expert/venvMaeteJag/lib/python3.10/site-packages/streamlit/runtime/state/safe_session_state.py", line 94, in __getitem__
    return self._state[key]
  File "/home/bc/Projects/meta_expert/venvMaeteJag/lib/python3.10/site-packages/streamlit/runtime/state/session_state.py", line 411, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "session_info_temp". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'

**Comment by Harold-lkk** [comment]
--model_format GPTAPI
the format for `GPTAPI` should be a dict config.

**Comment by MyraBaba** [comment]
@Harold-lkk 
python -m mindsearch.app --lang en --model_format GPTAPI


  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/bc/Projects/ODS/MindSearch/mindsearch/app.py", line 122, in run
    agent = init_agent(lang=args.lang, model_format=args.model_format)
  File "/home/bc/Projects/ODS/MindSearch/mindsearch/agent/__init__.py", line 24, in init_agent
    llm_cfg = llm_cfg.copy()
AttributeError: type object 'GPTAPI' has no attribute 'copy'



JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback:
File "/home/bc/Projects/meta_expert/venvMaeteJag/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 75, in exec_func_with_error_handling
    result = func()
File "/home/bc/Projects/meta_expert/venvMaeteJag/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 574, in code_to_exec
    exec(code, module.__dict__)
File "/home/bc/Projects/ODS/MindSearch/frontend/mindsearch_streamlit.py", line 319, in <module>
    main()
File "/home/bc/Projects/ODS/MindSearch/frontend/mindsearch_streamlit.py", line 314, in main
    update_chat(user_input)
File "/home/bc/Projects/ODS/MindSearch/frontend/mindsearch_streamlit.py", line 94, in update_chat
    for resp in streaming(raw_response):
File "/home/bc/Projects/ODS/MindSearch/frontend/mindsearch_streamlit.py", line 53, in streaming
    response = json.loads(decoded)
File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

**Comment by Harold-lkk** [comment]
please provide your added model config

**Comment by MyraBaba** [comment]
This my models.py 


import os

from lagent.llms import (GPTAPI, INTERNLM2_META, HFTransformerCasualLM,
                         LMDeployClient, LMDeployServer)

internlm_server = dict(type=LMDeployServer,
                       path='internlm/internlm2_5-7b-chat',
                       model_name='internlm2',
                       meta_template=INTERNLM2_META,
                       top_p=0.8,
                       top_k=1,
                       temperature=0,
                       max_new_tokens=8192,
                       repetition_penalty=1.02,
                       stop_words=['<|im_end|>'])

internlm_client = dict(type=LMDeployClient,
                       model_name='internlm2_5-7b-chat',
                       url='http://127.0.0.1:23333',
                       meta_template=INTERNLM2_META,
                       top_p=0.8,
                       top_k=1,
                       temperature=0,
                       max_new_tokens=8192,
                       repetition_penalty=1.02,
                       stop_words=['<|im_end|>'])

internlm_hf = dict(type=HFTransformerCasualLM,
                   path='internlm/internlm2_5-7b-chat',
                   meta_template=INTERNLM2_META,
                   top_p=0.8,
                   top_k=None,
                   temperature=1e-6,
                   max_new_tokens=8192,
                   repetition_penalty=1.02,
                   stop_words=['<|im_end|>'])

gpt4 = dict(type=GPTAPI,
            model_type='gpt-4-turbo',
            key='sk-jzI……………lbkFJl0wG…….xAsgXy7')

**Comment by MyraBaba** [comment]
@Harold-lkk  we impressed the seen demo and would love to test and use it . possibly we can support you.

Best

**Comment by bakongi** [comment]
Here is solution:
https://github.com/InternLM/MindSearch/issues/53

**Comment by liujiangning30** [comment]
Just `python -m mindsearch.app --lang en --model_format gpt4`

**Comment by MyraBaba** [comment]
streamlit problem solved

**Comment by Dany2018** [comment]
> 问题

请问你是如何解决的
