### ISSUE TITLE
ERROR:root:https://duckduckgo.com ConnectTimeout:

### ISSUE THREAD

**Issue by njzfw1024** [InternLM/MindSearch#59]
请问有什么解决办法吗
`ERROR:root:https://duckduckgo.com ConnectTimeout: 
Traceback (most recent call last):
  File "/opt/conda/envs/mindsearch/lib/python3.10/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/opt/conda/envs/mindsearch/lib/python3.10/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/opt/conda/envs/mindsearch/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/opt/conda/envs/mindsearch/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
  File "/opt/conda/envs/mindsearch/lib/python3.10/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/opt/conda/envs/mindsearch/lib/python3.10/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
  File "/opt/conda/envs/mindsearch/lib/python3.10/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "/opt/conda/envs/mindsearch/lib/python3.10/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
  File "/opt/conda/envs/mindsearch/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    with map_exceptions(exc_map):
  File "/opt/conda/envs/mindsearch/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/conda/envs/mindsearch/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout`

**Comment by Harold-lkk** [comment]
挂一个网络代理吧，你的网络ping不通搜索
