### ISSUE TITLE
terminal.py 调用外部工具ddg的时候报错了

### ISSUE THREAD

**Issue by lplzyp** [InternLM/MindSearch#61]
```
Traceback (most recent call last):
  File "E:\app\conda\envs\baize\lib\site-packages\lagent\actions\bing_browser.py", line 61, in search
    response = self._call_ddgs(query, timeout=self.timeout, proxy=self.proxy)
  File "E:\app\conda\envs\baize\lib\site-packages\lagent\actions\bing_browser.py", line 72, in _call_ddgs
    ddgs = DDGS(**kwargs)
  File "E:\app\conda\envs\baize\lib\site-packages\duckduckgo_search\duckduckgo_search.py", line 29, in __init__
    super().__init__(headers=headers, proxy=proxy, proxies=proxies, timeout=timeout)
  File "E:\app\conda\envs\baize\lib\site-packages\duckduckgo_search\duckduckgo_search_async.py", line 72, in __init__
    self._exception_event = asyncio.Event()
  File "E:\app\conda\envs\baize\lib\asyncio\locks.py", line 177, in __init__
    self._loop = events.get_event_loop()
  File "E:\app\conda\envs\baize\lib\asyncio\events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-1_0'.
```

**Comment by liujiangning30** [comment]
https://github.com/InternLM/lagent/pull/220

**Comment by lplzyp** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
