### ISSUE TITLE
Cuda Error

### ISSUE THREAD

**Issue by MyraBaba** [InternLM/MindSearch#73]
I have 16Gig nvida gpu still has belo error

```


`python -m mindsearch.terminal

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/bc/Projects/ODS/MindSearch/mindsearch/terminal.py", line 15, in <module>
    llm = LMDeployServer(path='internlm/internlm2_5-7b-chat',
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lagent/llms/lmdeploy_wrapper.py", line 310, in __init__
    import lmdeploy
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/__init__.py", line 3, in <module>
    from .api import client, pipeline, serve
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/api.py", line 5, in <module>
    from .messages import PytorchEngineConfig, TurbomindEngineConfig
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/messages.py", line 8, in <module>
    from .tokenizer import Tokenizer
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/tokenizer.py", line 8, in <module>
    import torch
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/torch/__init__.py", line 1382, in <module>
    from .functional import *  # noqa: F403
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/torch/functional.py", line 7, in <module>
    import torch.nn.functional as F
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
2024-08-03 17:28:46,033 - lmdeploy - WARNING - model_source: hf_model
2024-08-03 17:28:46,033 - lmdeploy - WARNING - model_name is deprecated in TurbomindEngineConfig and has no effect
Fetching 20 files: 100%|█████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 55406.92it/s]
Device does not support bf16.
2024-08-03 17:28:48,112 - lmdeploy - WARNING - model_config:

[llama]
model_name = internlm2
tensor_para_size = 1
head_num = 32
kv_head_num = 8
vocab_size = 92544
num_layer = 32
inter_size = 14336
norm_eps = 1e-05
attn_bias = 0
start_id = 1
end_id = 2
session_len = 32768
weight_type = fp16
rotary_embedding = 128
rope_theta = 1000000.0
size_per_head = 128
group_size = 0
max_batch_size = 128
max_context_token_num = 1
step_length = 1
cache_max_entry_count = 0.8
cache_block_seq_len = 128
cache_chunk_size = -1
num_tokens_per_iter = 0
max_prefill_iters = 1
extra_tokens_per_iter = 0
use_context_fmha = 1
quant_policy = 0
max_position_embeddings = 32768
rope_scaling_factor = 0.0
use_logn_attn = 0


[TM][WARNING] [LlamaTritonModel] `max_context_token_num` = 32768.
[TM][WARNING] [LlamaTritonModel] `num_tokens_per_iter` is not set, default to `max_context_token_num` (32768).
2024-08-03 17:28:48,182 - lmdeploy - WARNING - get 259 model params
Convert to turbomind format:   0%|                                                                                       | 0/32 [00:00<?, ?it/s]Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/serve/openai/api_server.py", line 1004, in serve
    VariableInterface.async_engine = AsyncEngine(
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py", line 68, in __init__
    self._build_turbomind(model_path=model_path,
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py", line 145, in _build_turbomind
    self.engine = tm.TurboMind.from_pretrained(
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 426, in from_pretrained
    return cls(model_path=pretrained_model_name_or_path,
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 195, in __init__
    self.model_comm = self._from_hf(model_source=model_source,
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 338, in _from_hf
    output_model.export()
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 257, in export
    self.export_misc(bin)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 288, in export_misc
    self.export_weight(emb, 'tok_embeddings.weight')
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 209, in export_weight
    torch_tensor = torch_tensor.half()
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 724.00 MiB. GPU 0 has a total capacty of 15.71 GiB of which 355.69 MiB is free. Including non-PyTorch memory, this process has 15.24 GiB memory in use. Of the allocated memory 724.00 MiB is allocated by PyTorch, and 0 bytes is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`
```

**Comment by Harold-lkk** [comment]
16G may be enough for the 7B model

**Comment by MyraBaba** [comment]
@Harold-lkk 

so why I have this error for python -m mindsearch.app --lang en --model_format internlm_server :

1. 
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 398, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53,
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/bc/Projects/ODS/MindSearch/mindsearch/app.py", line 122, in run
    agent = init_agent(lang=args.lang, model_format=args.model_format)
  File "/home/bc/Projects/ODS/MindSearch/mindsearch/agent/__init__.py", line 27, in init_agent
    llm = llm_cfg.pop('type')(**llm_cfg)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lagent/llms/lmdeploy_wrapper.py", line 310, in __init__
    import lmdeploy
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/__init__.py", line 3, in <module>
    from .api import client, pipeline, serve
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/api.py", line 5, in <module>
    from .messages import PytorchEngineConfig, TurbomindEngineConfig
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/messages.py", line 8, in <module>
    from .tokenizer import Tokenizer
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/tokenizer.py", line 8, in <module>
    import torch
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/torch/__init__.py", line 1382, in <module>
    from .functional import *  # noqa: F403
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/torch/functional.py", line 7, in <module>
    import torch.nn.functional as F
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
2024-08-05 19:04:44,850 - lmdeploy - WARNING - model_source: hf_model
2024-08-05 19:04:44,850 - lmdeploy - WARNING - model_name is deprecated in TurbomindEngineConfig and has no effect
Fetching 20 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 15744.38it/s]
Device does not support bf16.

model_name = internlm2
tensor_para_size = 1
head_num = 32
kv_head_num = 8
vocab_size = 92544
num_layer = 32
inter_size = 14336
norm_eps = 1e-05
attn_bias = 0
start_id = 1
end_id = 2
session_len = 32768
weight_type = fp16
rotary_embedding = 128
rope_theta = 1000000.0
size_per_head = 128
group_size = 0
max_batch_size = 128
max_context_token_num = 1
step_length = 1
cache_max_entry_count = 0.8
cache_block_seq_len = 128
cache_chunk_size = -1
num_tokens_per_iter = 0
max_prefill_iters = 1
extra_tokens_per_iter = 0
use_context_fmha = 1
quant_policy = 0
max_position_embeddings = 32768
rope_scaling_factor = 0.0
use_logn_attn = 0


[TM][WARNING] [LlamaTritonModel] `max_context_token_num` = 32768.
[TM][WARNING] [LlamaTritonModel] `num_tokens_per_iter` is not set, default to `max_context_token_num` (32768).
2024-08-05 19:04:46,832 - lmdeploy - WARNING - get 259 model params
Convert to turbomind format:   0%|                                                                                            | 0/32 [00:00<?, ?it/s]
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/serve/openai/api_server.py", line 1004, in serve
    VariableInterface.async_engine = AsyncEngine(
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py", line 68, in __init__
    self._build_turbomind(model_path=model_path,
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py", line 145, in _build_turbomind
    self.engine = tm.TurboMind.from_pretrained(
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 426, in from_pretrained
    return cls(model_path=pretrained_model_name_or_path,
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 195, in __init__
    self.model_comm = self._from_hf(model_source=model_source,
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 338, in _from_hf
    output_model.export()
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 257, in export
    self.export_misc(bin)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 288, in export_misc
    self.export_weight(emb, 'tok_embeddings.weight')
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 203, in export_weight
    torch_tensor = param.cuda().contiguous()
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 724.00 MiB. GPU 0 has a total capacty of 15.71 GiB of which 612.06 MiB is free. Process 9463 has 118.68 MiB memory in use. Including non-PyTorch memory, this process has 14.53 GiB memory in use. Of the allocated memory 0 bytes is allocated by PyTorch, and 0 bytes is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
^C
^C^C
 4  0:docker -   1:python *   2:python3                                                                                          2024-08-05 19:05:59
To see these additional updates run: apt list --upgradable

48 additional security updates can be applied with ESM Apps.
Learn more about enabling ESM Apps service at https://ubuntu.com/esm


23 updates could not be installed automatically. For more details,
see /var/log/unattended-upgrades/unattended-upgrades.log

4 devices have a firmware upgrade available.
Run `fwupdmgr get-upgrades` for more information.

Last login: Mon Aug  5 17:28:48 2024 from 192.168.5.109
bc@bc:~$ tmux
[exited]
bc@bc:~$ nvim .tmux.conf
bc@bc:~$ zsh
bc@bc ~ % tmux
[exited]
bc@bc ~ % tmux source ~/.tmux.conf
'~/.tmux/plugins/tpm/tpm' returned 126
bc@bc ~ % chmod +x ~/.tmux/plugins/tpm/tpm

bc@bc ~ % tmux source ~/.tmux.conf
bc@bc ~ % tmux
[detached (from session 4)]
bc@bc ~ % top
top - 19:06:21 up  8:08,  6 users,  load average: 0,17, 0,26, 0,34
Tasks: 374 total,   1 running, 373 sleeping,   0 stopped,   0 zombie
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/serve/openai/api_server.py", line 1004, in serve
    VariableInterface.async_engine = AsyncEngine(
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py", line 68, in __init__
    self._build_turbomind(model_path=model_path,
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py", line 145, in _build_turbomind
    self.engine = tm.TurboMind.from_pretrained(
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 426, in from_pretrained
    return cls(model_path=pretrained_model_name_or_path,
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 195, in __init__
    self.model_comm = self._from_hf(model_source=model_source,
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 338, in _from_hf
    output_model.export()
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 257, in export
    self.export_misc(bin)
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 288, in export_misc
    self.export_weight(emb, 'tok_embeddings.weight')
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 203, in export_weight
    torch_tensor = param.cuda().contiguous()
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 724.00 MiB. GPU 0 has a total capacty of 15.71 GiB of which 612.06 MiB is free. Process 9463 has 118.68 MiB memory in use. Including non-PyTorch memory, this process has 14.53 GiB memory in use. Of the allocated memory 0 bytes is allocated by PyTorch, and 0 bytes is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
^C
^C^Czsh: killed     python -m mindsearch.app --lang en --model_format internlm_server

**Comment by MyraBaba** [comment]
how much memory min we need for this model ?
