### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by MyraBaba** [InternLM/MindSearch#75]
Finally MindSearch worked gpt4 and streamlit 

som question it gives:

<|action_start|><|interpreter|>
```python
graph = WebSearchGraph()
graph.add_root_node(node_content="What is the 10 top topic in UK last week?", node_name="root")
graph.add_node(
    node_name="Top Topics Source",
    node_content="What are the sources for finding the top topics in UK last week?")
# Get node info
graph.node("Top Topics Source")
```
<|action_end|>
current query: ## Final Problem
What is the 10 top topic in UK last week?
## Current Problem
What are the sources for finding the top topics in UK last week?

To find the top topics in UK from last week, several reliable sources can be utilized:

1. **Google Trends**: This tool analyzes the popularity of top search queries in Google Search across various regions and languages. It provides a list of trending topics for a specific region and timeframe.

2. **Twitter Trends**: Twitter often provides real-time data on trending topics and hashtags that are popular in specific regions, including UK.

3. **Local News Websites**: Websites like Hurriyet Daily News, Daily Sabah, or Anadolu Agency often publish articles on current events and popular topics in UK.

4. **Social Media Analytics Tools**: Tools like Brandwatch or Socialbakers can analyze social media data to find trending topics based on user engagement and discussions.

5. **TV and Radio News Outlets**: Major UK broadcasters like BBC or CNN UK often cover the most relevant and trending topics in their news segments.

These sources collectively offer a comprehensive view of the most discussed and trending topics in UK for any given week.
ERROR:root:Exception in sync_generator_wrapper: list index out of range
Traceback (most recent call last):
  File "/home/bc/Projects/ODS/MindSearch/mindsearch/app.py", line 68, in sync_generator_wrapper
    for response in agent.stream_chat(inputs):
  File "/home/bc/Projects/ODS/MindSearch/mindsearch/agent/mindsearch_agent.py", line 237, in stream_chat
    yield from self._process_code(agent_return, inner_history,
  File "/home/bc/Projects/ODS/MindSearch/mindsearch/agent/mindsearch_agent.py", line 284, in _process_code
    reference, references_url = self._generate_reference(
  File "/home/bc/Projects/ODS/MindSearch/mindsearch/agent/mindsearch_agent.py", line 315, in _generate_reference
    ref_results = agent_return.nodes[node_name]['detail'].actions[
IndexError: list index out of range

**Comment by bakongi** [comment]
Check this:
https://github.com/InternLM/MindSearch/issues/53

**Comment by MyraBaba** [comment]
after modified as in #53 try blocked the error but web UI waiting stucking without clue.
model gpt-4o-mini
we have time to time errors:

ERROR:mindsearch.agent.mindsearch_agent:Error in model_stream_thread: 'content'
Traceback (most recent call last):
  File "/home/bc/Projects/ODS/MindSearch/mindsearch/agent/mindsearch_agent.py", line 148, in model_stream_thread
    for answer in agent.stream_chat(
  File "/home/bc/Projects/ODS/MindSearch/mindsearch/agent/mindsearch_agent.py", line 46, in stream_chat
    for agent_return in super().stream_chat(message,
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lagent/agents/internlm2_agent.py", line 303, in stream_chat
    for model_state, res, _ in self._llm.stream_chat(prompt, **kwargs):
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lagent/llms/openai.py", line 151, in stream_chat
    for text in self._stream_chat(messages, **gen_params):
  File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lagent/llms/openai.py", line 288, in streaming
    yield choice['delta']['content']
**KeyError: 'content'**



ERROR:root:Exception in sync_generator_wrapper: list index out of range
Traceback (most recent call last):
  File "/home/bc/Projects/ODS/MindSearch/mindsearch/app.py", line 68, in sync_generator_wrapper
    for response in agent.stream_chat(inputs):
  File "/home/bc/Projects/ODS/MindSearch/mindsearch/agent/mindsearch_agent.py", line 237, in stream_chat
    yield from self._process_code(agent_return, inner_history,
  File "/home/bc/Projects/ODS/MindSearch/mindsearch/agent/mindsearch_agent.py", line 284, in _process_code
    reference, references_url = self._generate_reference(
  File "/home/bc/Projects/ODS/MindSearch/mindsearch/agent/mindsearch_agent.py", line 373, in _generate_reference
    ref_results = agent_return.nodes[node_name]['detail'].actions[
**IndexError: list index out of range**

**Comment by jamesfebin** [comment]
Facing same issue

**Comment by FellowTraveler** [comment]
Same issue here with latest code. Will check #53 and #87.

```
python -m mindsearch.app --lang en --model_format gpt4
INFO:     Started server process [76373]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8002 (Press CTRL+C to quit)
INFO:     127.0.0.1:60637 - "POST /solve HTTP/1.1" 200 OK
/opt/miniconda3/envs/mindsearch_env/lib/python3.12/site-packages/lagent/llms/openai.py:397: DeprecationWarning: `top_k` parameter is deprecated in OpenAI APIs.
  warnings.warn(
To effectively address the inquiry about current prices for late-model Ford F-150s in Austin, TX, we'll begin by structuring our search graph to break down the question into manageable sub-questions.

1. Identify what constitutes a "late-model" for Ford F-150s.
2. Search for the current prices of these models in Austin, TX.

Let's start by defining "late-model" in the context of Ford F-150 trucks.

<|action_start|><|interpreter|>
```python
graph = WebSearchGraph()
graph.add_root_node(node_content="What is considered a late-model for Ford F-150s?", node_name="root")
```
<|action_end|>
Next, we will query the current prices of these defined late-model Ford F-150 trucks specifically in the Austin, TX market.

<|action_start|><|interpreter|>
```python
graph.add_node(
    node_name="Ford F-150 Prices in Austin", 
    node_content="What are the current prices for late-model Ford F-150s in Austin, TX?"
)
graph.add_edge(start_node="root", end_node="Ford F-150 Prices in Austin")
# Get new added node information
graph.node("Ford F-150 Prices in Austin")
```<|action_end|>
current query: ## Final Problem
What is considered a late-model for Ford F-150s?
## Current Problem
What are the current prices for late-model Ford F-150s in Austin, TX?

To answer the question about the current prices for late-model Ford F-150s in Austin, TX, I'll first need to search for relevant information online. I will look up the latest available prices for Ford F-150 models in the Austin area.

Let's proceed with the search.
ERROR:root:Exception in sync_generator_wrapper: list index out of range
Traceback (most recent call last):
  File "/Users/au/src/MindSearch/mindsearch/app.py", line 68, in sync_generator_wrapper
    for response in agent.stream_chat(inputs):
  File "/Users/au/src/MindSearch/mindsearch/agent/mindsearch_agent.py", line 237, in stream_chat
    yield from self._process_code(agent_return, inner_history,
  File "/Users/au/src/MindSearch/mindsearch/agent/mindsearch_agent.py", line 284, in _process_code
    reference, references_url = self._generate_reference(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/au/src/MindSearch/mindsearch/agent/mindsearch_agent.py", line 315, in _generate_reference
    ref_results = agent_return.nodes[node_name]['detail'].actions[
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
```

**Comment by MyraBaba** [comment]
@liujiangning30 

still same issue:  model gpt4 

> ERROR:root:Exception in sync_generator_wrapper: list index out of range
Traceback (most recent call last):
  File "/home/bc/Projects/ODS/MindSearch/mindsearch/app.py", line 68, in sync_generator_wrapper
    for response in agent.stream_chat(inputs):
  File "/home/bc/Projects/ODS/MindSearch/mindsearch/agent/mindsearch_agent.py", line 237, in stream_chat
    yield from self._process_code(agent_return, inner_history,
  File "/home/bc/Projects/ODS/MindSearch/mindsearch/agent/mindsearch_agent.py", line 284, in _process_code
    reference, references_url = self._generate_reference(
  File "/home/bc/Projects/ODS/MindSearch/mindsearch/agent/mindsearch_agent.py", line 373, in _generate_reference
    ref_results = agent_return.nodes[node_name]['detail'].actions[
IndexError: list index out of range

**Comment by liujiangning30** [comment]
> @liujiangning30
> 
> still same issue: model gpt4
> 
> > ERROR:root:Exception in sync_generator_wrapper: list index out of range
> > Traceback (most recent call last):
> > File "/home/bc/Projects/ODS/MindSearch/mindsearch/app.py", line 68, in sync_generator_wrapper
> > for response in agent.stream_chat(inputs):
> > File "/home/bc/Projects/ODS/MindSearch/mindsearch/agent/mindsearch_agent.py", line 237, in stream_chat
> > yield from self._process_code(agent_return, inner_history,
> > File "/home/bc/Projects/ODS/MindSearch/mindsearch/agent/mindsearch_agent.py", line 284, in _process_code
> > reference, references_url = self._generate_reference(
> > File "/home/bc/Projects/ODS/MindSearch/mindsearch/agent/mindsearch_agent.py", line 373, in _generate_reference
> > ref_results = agent_return.nodes[node_name]['detail'].actions[
> > IndexError: list index out of range

https://github.com/InternLM/MindSearch/issues/75#issuecomment-2268273337
