### ISSUE TITLE
RuntimeError: Operation on the closed queue is forbidden

### ISSUE THREAD

**Issue by luyizhou6126214** [InternLM/MindSearch#77]
windows和Linux下运行都出现这个

ERROR:root:Exception in sync_generator_wrapper: Operation on the closed queue is forbidden
Traceback (most recent call last):
  File "/workspace/MindSearch/mindsearch/app.py", line 69, in sync_generator_wrapper
    queue.sync_q.put(response)
  File "/root/miniconda3/envs/mindsearch/lib/python3.10/site-packages/janus/__init__.py", line 371, in put
    self._parent._check_closing()
  File "/root/miniconda3/envs/mindsearch/lib/python3.10/site-packages/janus/__init__.py", line 269, in _check_closing
    raise RuntimeError("Operation on the closed queue is forbidden")
RuntimeError: Operation on the closed queue is forbidden
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=RuntimeError('Operation on the closed queue is forbidden')>
Traceback (most recent call last):
  File "/root/miniconda3/envs/mindsearch/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/workspace/MindSearch/mindsearch/app.py", line 75, in sync_generator_wrapper
    queue.sync_q.put(None)
  File "/root/miniconda3/envs/mindsearch/lib/python3.10/site-packages/janus/__init__.py", line 371, in put
    self._parent._check_closing()
  File "/root/miniconda3/envs/mindsearch/lib/python3.10/site-packages/janus/__init__.py", line 269, in _check_closing
    raise RuntimeError("Operation on the closed queue is forbidden")
RuntimeError: Operation on the closed queue is forbidden

**Comment by luyizhou6126214** [comment]
没法运行啊

**Comment by sanwacompany** [comment]
> #84

大佬果然6。按照这个方法改了，顺利跑起来了。
