### ISSUE TITLE
搜索不出来结果。

### ISSUE THREAD

**Issue by sanwacompany** [InternLM/MindSearch#80]
输入关键词搜索，一直在这个界面，就是不出来结果。

windows10系统，在Python3.9虚拟环境下部署的。模型选择了gpt4, 已经在models.py中填入自己的openai key

![image](https://github.com/user-attachments/assets/327aab0c-3b4f-4089-b6df-8ef5d9ea9226)

(venv) ~\PycharmProjects\Mindsearch
python -m mindsearch.app --lang zh --model_format gpt4
INFO:     Started server process [11256]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8002 (Press CTRL+C to quit)
INFO:     127.0.0.1:57333 - "POST /solve HTTP/1.1" 200 OK
ERROR:root:Exception in sync_generator_wrapper: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Traceback (most recent call last):
  File "C:\Users\59722\PycharmProjects\Mindsearch\mindsearch\app.py", line 68, in sync_generator_wrapper
    for response in agent.stream_chat(inputs):
  File "C:\Users\59722\PycharmProjects\Mindsearch\mindsearch\agent\mindsearch_agent.py", line 214, in stream_chat
    for model_state, response, _ in self.llm.stream_chat(
  File "C:\Users\59722\PycharmProjects\Mindsearch\venv\lib\site-packages\lagent\llms\openai.py", line 157, in stream_chat
    for text in self._stream_chat(messages, **gen_params):
  File "C:\Users\59722\PycharmProjects\Mindsearch\venv\lib\site-packages\lagent\llms\openai.py", line 288, in streaming
    response = json.loads(decoded)
  File "C:\Users\59722\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\59722\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\59722\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

**Comment by Harold-lkk** [comment]
May update `lagent` version. Sorry for the bad experience; we will provide a tag for an easier start.
