### ISSUE TITLE
跑起来了，但是跑了几步后又没动静了 ERROR:mindsearch.agent.mindsearch_agent:Error in model_stream_thread: 'content'

### ISSUE THREAD

**Issue by sanwacompany** [InternLM/MindSearch#92]
整体卫浴的分类主要包括以下几种[[4]]:
1. **FRP整体卫浴**：使用玻璃钢材料，这种材料轻便且具有良好的防水性能。
2. **SMC整体卫浴**：采用Sheet Molding Compound（片状模塑复合材料）制造，具有高强度和良好的耐久性。
3. **彩钢板整体卫浴**：使用彩色钢板，外观多样化，可满足不同的装饰风格需求。
4. **瓷砖墙板整体卫浴**：使用瓷砖作为墙板材料，具有更传统的外观和感觉，同时保持了整体卫浴的便利性。

整体卫浴因其安装快速、维护简便、防水性能好等优点，越来越受到现代家庭的欢迎。
ERROR:mindsearch.agent.mindsearch_agent:Error in model_stream_thread: 'content'
Traceback (most recent call last):
  File "/home/gamma/MindSearch/mindsearch/agent/mindsearch_agent.py", line 148, in model_stream_thread
    for answer in agent.stream_chat(
  File "/home/gamma/MindSearch/mindsearch/agent/mindsearch_agent.py", line 46, in stream_chat
    for agent_return in super().stream_chat(message,
  File "/home/gamma/MindSearch/venv/lib/python3.12/site-packages/lagent/agents/internlm2_agent.py", line 303, in stream_chat
    for model_state, res, _ in self._llm.stream_chat(prompt, **kwargs):
  File "/home/gamma/MindSearch/venv/lib/python3.12/site-packages/lagent/llms/openai.py", line 151, in stream_chat
    for text in self._stream_chat(messages, **gen_params):
  File "/home/gamma/MindSearch/venv/lib/python3.12/site-packages/lagent/llms/openai.py", line 288, in streaming
    yield choice['delta']['content']
          ~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'content'
已构建了搜索图来逐步获取整体卫浴行业的详细信息。接下来，我们可以通过查询各个节点来获取具体的数据和信息。如果需要进一步查询或有其他问题，请告诉我！
请问是什么情况？

**Comment by liujiangning30** [comment]
Please check the specifics of the `choice['delta']`

**Comment by sanwacompany** [comment]
> Please check the specifics of the `choice['delta']`

thank u for rely, but how? the code in openai.py is like this:

**Comment by liujiangning30** [comment]
Just `print(choice['delta'])` or check this [pr](https://github.com/InternLM/lagent/pull/225/files)
