### ISSUE TITLE
用qwen运行之后报错

### ISSUE THREAD

**Issue by qql828** [InternLM/MindSearch#98]
ERROR:root:Exception in sync_generator_wrapper: 'output'
Traceback (most recent call last):
  File "/Users/qinql/github/ai-search/MindSearch/mindsearch/app.py", line 68, in sync_generator_wrapper
    for response in agent.stream_chat(inputs):
  File "/Users/qinql/github/ai-search/MindSearch/mindsearch/agent/mindsearch_agent.py", line 214, in stream_chat
    for model_state, response, _ in self.llm.stream_chat(
  File "/Users/qinql/.pyenv/versions/3.11.2/lib/python3.11/site-packages/lagent/llms/openai.py", line 151, in stream_chat
    for text in self._stream_chat(messages, **gen_params):
  File "/Users/qinql/.pyenv/versions/3.11.2/lib/python3.11/site-packages/lagent/llms/openai.py", line 281, in streaming
    choice = response['output']['choices'][0]
             ~~~~~~~~^^^^^^^^^^
KeyError: 'output'


把response输出来是，response= {'code': 'InvalidParameter', 'message': 'messages with role "tool" must be a response to a preceeding message with "tool_calls".', 'request_id': '01b3bac1-e311-98be-b818-0ab0b2beec3f'}

![WechatIMG1](https://github.com/user-attachments/assets/a406b5f1-589b-4883-978e-b8731102d186)

**Comment by liujiangning30** [comment]
https://github.com/InternLM/lagent/pull/225
